version: '3'

services:
  postgres:
    build:
      context: ./database
    ports:
      - 5432:5432
    networks:
      - mynetwork
    restart: unless-stopped


  backend:
    build:
      context: ./flaskbackend
    ports:
      - 5000:5000
    depends_on:
      - postgres
    networks:
      - mynetwork
    restart: unless-stopped


  frontend:
    build:
      context: ./reactfrontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork
    restart: unless-stopped
    links:
      - backend
      

  

networks:
  mynetwork:
