version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
