version: '3'
services:
  flask-app:
    build:
      context: ./flaskbackend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - sqlite-db

  sqlite-db:
    build:
      context: ./sqlite
      dockerfile: Dockerfile-sqlite
