version: '3'
services:
  flask-app:
    build:
      context: ./flaskbackend
      dockerfile: Dockerfile-flask
    ports:
      - "5000:5000"
    depends_on:
      - sqlite-db

  sqlite-db:
    build:
      context: ./sqlite
      dockerfile: Dockerfile-sqlite

  reactfrontend:
    build:
      context: ./reactfrontend
      dockerfile: Dockerfile-react
    ports:
      - "3000:3000"
