version: '3'

services:
  frontend:
    build:
      context: ./reactfrontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    build:
      context: ./database
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./flaskbackend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
