version: '3'
services:
  flask-app:
    build:
      context: ./flaskbackend
      dockerfile: Dockerfile-flask
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    build: ./database 
    ports:
      - "5432:5432"

  reactfrontend:
    build:
      context: ./reactfrontend
      dockerfile: Dockerfile-react
    ports:
      - "3000:3000"
