# Dockerfile-react
FROM node:14-alpine

# Set the working directory to the current directory
WORKDIR .

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the app source code to the container
COPY . .

# Expose the port on which the app will run
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
