# Dockerfile-database
FROM sqlite:3.36.0

# Set the working directory
WORKDIR .

# Copy the SQLite database file into the container
COPY tasklist.db /tasklist.db

# Copy the SQL initialization script
COPY init.sql /docker-entrypoint-initdb.d/
